# Generated by Django 3.2.7 on 2022-03-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_teamscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamscore',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreteam', to='game.team', unique=True),
        ),
    ]
