# Generated by Django 4.0.3 on 2022-05-29 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_team_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('intro', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='module_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_game', to='game.game', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='module_segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('training_video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='module_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.TextField(max_length=1000)),
                ('right_answer', models.CharField(default='Y', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_questions', to='game.module_game')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_questions', to='game.module_segment')),
            ],
        ),
    ]
