# Generated by Django 4.0.3 on 2022-05-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_module_module_game_module_segment_module_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_game',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module_segment',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='game.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module_game',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_games', to='game.game', unique=True),
        ),
    ]
