# Generated by Django 4.0.3 on 2022-05-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_module_game_module_module_segment_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='module_questions',
            field=models.ManyToManyField(to='game.module_question'),
        ),
    ]
