# Generated by Django 4.0.3 on 2022-06-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_game_training_video_game_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='video',
            new_name='training_video',
        ),
    ]
