# Generated by Django 4.0.3 on 2022-06-04 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_video_game_training_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='training_video',
        ),
        migrations.AddField(
            model_name='game',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
