# Generated by Django 4.0.3 on 2022-06-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_module_question_option_a_module_question_option_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_text', models.TextField(max_length=1000)),
            ],
        ),
    ]
